---
version: "1.5"

services:
  web:
    image: docker.io/jackzampolin/jackserver:latest
    expose:
      - port: 3000
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      cpu: 0.1
      memory: 16Mi
      storage: 128Mi
  placement:
    westcoast:
      attributes:
        region: us-west
      pricing:
        web: 
          denom: akash 
          amount: 3920

deployment:
  web:
    westcoast:
      profile: web
      count: 1
